import { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import StCard from '../components/stCard';
import LineCard from '../components/lineCard';
import LineLoginCard from '../components/lineLoginCard';
import AppointCard from '../components/appointCard';
import { useAppDispatch } from '../hooks/useRTK';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  useEffect(() => {
    // Check to see if this is a redirect back from Checkout
    const query = new URLSearchParams(window.location.search);
    if (query.get('success')) {
      console.log('Order placed! You will receive an email confirmation.');
    }

    if (query.get('canceled')) {
      console.log(
        'Order canceled -- continue to shop around and checkout when you’re ready.'
      );
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <StCard name="stripe" />
      </main>
      <main className={styles.main}>
        <LineCard name="line" />
      </main>
      <main className={styles.main}>
        <AppointCard name="appoint" />
      </main>
      <main className={styles.main}>
        <LineLoginCard name="line login" dispatch={dispatch} />
      </main>
    </div>
  );
};

export default Home;
